name: DEV CI

on:
  pull_request:
    branches:
      - develop

jobs:
  Run-PR-Test:
    name: Lint & Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle
        with:
          base-url: ${{ secrets.BASE_URL }}
          base-url-dev: ${{ secrets.BASE_URL_DEV }}
          image-base-url: ${{ secrets.IMAGE_BASE_URL }}
          image-base-url-dev: ${{ secrets.IMAGE_BASE_URL_DEV }}
          naver-map-client-id: ${{ secrets.NAVER_MAP_CLIENT_ID }}
          naver-map-style-id: ${{ secrets.NAVER_MAP_STYLE_ID }}
          app-bundle-id: ${{ secrets.APP_BUNDLE_ID }}
          app-bundle-id-dev: ${{ secrets.APP_BUNDLE_ID_DEV }}
          store-password: ${{ secrets.STORE_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Generate BuildKonfig
        run: ./gradlew :composeApp:generateBuildKonfig -Pbuildkonfig.flavor=dev

      - name: Run ktlint
        run: ./gradlew ktlintCheck -Pbuildkonfig.flavor=dev

      - name: Run unit tests
        run: ./gradlew :composeApp:allTest -Pbuildkonfig.flavor=dev

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: composeApp/build/test-results/**/*.xml
          check_name: '테스트 결과 (DEV) 🛠️'
          comment_mode: 'off'
